server:
  port: 9090
  servlet:
    context-path: /momentum-active-shoppe
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:active_shoppe_db
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: MomentumActiveShoppeApplication
